# Workflow for testing Spoon.
#
# Note that actions are specified by commit hash. This is to avoid the security
# risk of someone injecting malicious code into a release and then simply
# changing a tag.!

name: tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
  - cron: "0 0 * * *"

env:
  JAVA_DISTRIBUTION: temurin

jobs:
  code-quality: # we create a new step here because qodana analyzer takes around 10min
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      QODANA_LINTER: jetbrains/qodana-jvm-community:2021.3
    name: code-quality qodana
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          path: pull_request
      - uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf # renovate: tag=v2.5.0
        with:
          java-version: 17
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: git reset
        run: cd pull_request && git fetch && git reset --soft origin/master
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@6df92dd1240ad63ed7956fa74069d636067d574d # renovate: tag=v4.2.5
        continue-on-error: true
        with:
          linter: ${{ env.QODANA_LINTER }}
          project-dir: "${{ github.workspace }}/pull_request"
          inspected-dir: ./src/main/java # only main spoon project at first
          results-dir:  "${{ github.workspace }}/result"
          changes: false
          fail-threshold: 0
          upload-result: false
      - name: Upload as artifact for later workflow
        uses: actions/upload-artifact@v2
        with:
          name: qodana-sarif
          path: ${{ github.workspace }}/result/qodana.sarif.json
