name: Upload qodana sarif

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  upload-qodana-sarif:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: qodana-sarif
          path: sarif
          workflow_conclusion: success
      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif/qodana.sarif.json
